### Get all parking

GET http://localhost:3000/admin/parkings/ HTTP/1.1

###
### Create Parking

POST http://localhost:3000/admin/parkings/ HTTP/1.1
content-type: application/json

{
    "name": "test parking 1",
    "description": "test parking 1"
}

###
### Get All floor
GET http://localhost:3000/admin/floors/ HTTP/1.1

###
### Create floor
POST http://localhost:3000/admin/floors/ HTTP/1.1
content-type: application/json

{
    "name": "B",
    "parkingId": 1
}

###
### Get All Slot
GET http://localhost:3000/admin/slots/ HTTP/1.1

###
### Create Slot
POST http://localhost:3000/admin/slots/ HTTP/1.1
content-type: application/json

{
    "name": "B6",
    "floorId": 4,
    "isAvailable": false,
    "type": "FourWheeler"
}